config/routes.rb
Rails.application.routes.draw do
  #get '/cards/random' => 'cards#random'
  resources :cards do
    get 'random', on: :collection
  end

  root 'cards#index'
  
  resources :sessions, only: [:new, :create]
  get '/sign_out' => 'sessions#destroy', as: :sign_out
end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :question, :answer, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password

  validates :username, presence: true, uniqueness: true

  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,
                                                    password_salt)
  end

  def self.authenticate(username, password)
    user = where(username: username).first
    if user && user.password_hash ==
               BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  layout 'application'

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all.paginate(page: params[:page], per_page: 50)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end
  
  # GET /cards/random
  def random
    @card = Card.find(Card.all.pluck(:id).sample)
  end

  # GET /cards/new
  def new
    if current_user
      @card = Card.new
    else
      redirect_to root_path, warning: 'Not for you.'
    end
  end

  # GET /cards/1/edit
  def edit
    if current_user
      @card = Card.find(params[:id])
    else
      @card = nil
      redirect_to root_path, warning: 'Not for you.'
    end
  end

  # POST /cards
  # POST /cards.json
  def create
    if current_user
      @card = Card.new(card_params)

      respond_to do |format|
        if @card.save
          format.html do
            flash[:success] = 'Card was successfully created.' 
            redirect_to new_card_path            
          end
          format.json { render :show, status: :created, location: @card }
        else
          format.html { render :new }
          format.json { render json: @card.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, warning: 'Not for you.'
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    if current_user
      respond_to do |format|
        if @card.update(card_params)
          format.html { redirect_to @card, notice: 'Card was successfully updated.' }
          format.json { render :show, status: :ok, location: @card }
        else
          format.html { render :edit }
          format.json { render json: @card.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, warning: 'Not for you.'
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    if current_user
      @card.destroy
      respond_to do |format|
        format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, warning: 'Not for you.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:question, :answer, :citation)
    end
end

app/controllers/sessions_controller.rb
# sessions controller
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:username], params[:password])
    if @user
      flash[:success] = 'log in successful'
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:warning] = 'sign in failed'
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'sign out successful'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.haml
= form_for @card do |f|
  - if @card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@card.errors.count, "error")} prohibited this card from being saved:"
      %ul
        - @card.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :question
    %br
    = f.text_area :question, rows: '3', cols: '50'
  .field
    = f.label :answer
    %br
    = f.text_area :answer, rows: '3', cols: '50'
  .field
    = f.label :citation
    %br
    = f.text_area :citation, rows: '3', cols: '50'
  .actions
    = f.submit 'Save'

app/views/cards/edit.html.haml
%h1 Editing card

= render 'form'

= link_to 'Show', @card
\|
= link_to 'Back', cards_path

app/views/cards/index.html.haml
%h1 Listing cards

%table
  %thead
    %tr
      %th Question
      %th Answer
      %th Citation
      %th
      %th
      %th
      
  %tbody
    - @cards.each do |card|
      %tr
        %td= card.question.truncate(40)
        %td= card.answer.truncate(40)
        %td= link_to 'Source', card.citation, target: '_blank'
        %td= link_to 'Show', card
        %td= link_to 'Edit', edit_card_path(card) if current_user
        %td= link_to 'Destroy', card, method: :delete, data: {confirm: 'Are you sure?' } if current_user

%br
= will_paginate @cards
%br
= link_to 'New Card', new_card_path

app/views/cards/new.html.haml
%h1 New card

= render 'form'

= link_to 'Back', cards_path

app/views/cards/random.html.haml
%p#notice= notice

%p
  %b Question:
  = @card.question
#response
  %p
    %b Response:
  %textarea{'class'=>'response_text','rows'=>'3','cols'=>'50','autocomplete'=>'false'}
=submit_tag 'show answer', type: 'button', id: 'show_answer'    
=submit_tag 'try again', type: 'button', id: 'try_again_btn'
.answer(data-ans="#{@card.answer}")
  %p
    %b Answer:
    = @card.answer
%p
  %b Citation:
  = link_to 'Source', @card.citation, target: '_blank'
%p
  = link_to 'Next', random_cards_path, id: 'next_btn'
= link_to 'Edit', edit_card_path(@card) if current_user
= '|' if current_user
= link_to 'Back', cards_path

app/views/cards/show.html.haml
%p#notice= notice

%p
  %b Question:
  = @card.question
%p
  %b Answer:
  = @card.answer
%p
  %b Citation:
  = link_to 'Source', @card.citation, target: '_blank'
%p
  
= link_to 'Edit', edit_card_path(@card) if current_user
= '|' if current_user
= link_to 'Back', cards_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      Flashcard
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body>
    = render 'shared/navigation'
    %hr
    - if flash.present?
      - flash.each do |k, v|
        = v
        %br
      %hr
    = yield

app/views/shared/_navigation.html.haml
= link_to 'Flashcards', root_path
&nbsp;|&nbsp;
= link_to 'Begin', random_cards_path
&nbsp;|&nbsp;
- if current_user
  = link_to 'new card', new_card_path
  &nbsp;|&nbsp;
  = "#{current_user.username}"
  &nbsp;|&nbsp;
  = link_to 'sign out', sign_out_path
- else
  = "Guest"
  &nbsp;|&nbsp;
  = link_to 'auth', new_session_path